# @package _global_.scheduler

# Learning rate scheduler settings
use_scheduler: true
type: cosine  # Options: cosine, step, reduce_on_plateau
min_lr: 1e-9

# New parameter for cosine warmup
warmup_ratio: 0  # 1% of training for warmup phase

# Parameters for step scheduler
step_size: 20
gamma: 0.1

# Parameters for reduce_on_plateau scheduler
factor: 0.5
patience: 5