# @package _global_.model

# Model architecture parameters
analysis_dim: 224
patch_size: [7, 7]
embed_dim: 1024
depth: 10
num_heads: 16
decoder_embed_dim: 512
decoder_depth: 4
decoder_num_heads: 8
mlp_ratio: 4.0
num_frames: 30
t_patch_size: 5
in_chans: 1
aux_chans: 1
aux_embed_dim: 256
temperature: 0.2
mask_ratio: 0.5

# Contrastive learning mode: 'global' or 'spatial'
contrastive_mode: global

# Whether to use thickness mask for excluding black rim regions
use_thickness_mask: true

# Diversity loss weights
intra_div_weight: 0.1  # Weight for intra-patch diversity loss
inter_div_weight: 0.1  # Weight for inter-patch diversity loss

# Loss weights
loss_weights:
  recon: 1.0
  contrastive: 0.3

use_multimodal: false