# @package _global_

# Hydra configuration
hydra:
  run:
    dir: eval_outputs/${now:%Y-%m-%d}/${experiment_name}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${experiment_name}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Set default paths and experiment name
defaults:
  - _self_
  - model: spectral_gpt
  - data: eval_data
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

# General settings
seed: 42
device: cuda
experiment_name: spectralgpt_evaluation

# Evaluation settings
evaluation:
  checkpoint_path: "outputs/latest/checkpoints/best_model.pth"
  batch_size: 8
  visualize_embeddings: true

# Logging settings
logging:
  use_mlflow: true
  experiment_name: ${experiment_name}
  run_name: "evaluation_${now:%Y-%m-%d_%H-%M-%S}"