# @package _global_

# Hydra configuration
hydra:
  run:
    dir: Z:/Projects/Ophthalmic neuroscience/Projects/Kayvan/MMG_Spectral_Output/${now:%Y-%m-%d}/${experiment_name}/${now:%H-%M-%S}
    #outputs/${now:%Y-%m-%d}/${experiment_name}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${experiment_name}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Set default paths and experiment name
defaults:
  - _self_
  - model: spectral_gpt
  - data: default
  - optimizer: adamw
  - scheduler: cosine
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

# General settings
seed: 42
device: cuda
experiment_name: spectralgpt_mae_contrastive

# Training settings
training:
  epochs: 100
  batch_size: 2
  resume_from_checkpoint: false
  checkpoint_path: "Z:/Projects/Ophthalmic neuroscience/Projects/Kayvan/MMG_Spectral_Output/2025-03-28/spectralgpt_mae_contrastive/23-15-43/checkpoints/best_model.pth"
  early_stopping:
    enabled: false
    patience: 50
    min_delta: 0.001



# Logging settings
logging:
  use_mlflow: true
  experiment_name: ${experiment_name}
  run_name: ${now:%Y-%m-%d_%H-%M-%S}
  log_freq: 1

# Visualization settings
visualization:
  viz_frequency: 1
  add_numerical_viz: true  # Enable numerical visualization
  num_samples: 2
  include_aux: true